export const FETCH_PEOPLE = 'FETCH_PEOPLE';
export const FETCH_PLANETS = 'FETCH_PLANETS';
export const RESET_FETCH_ACTION = 'RESET_FETCH_ACTION';
export const PLAYER_LOG = 'PLAYER_LOG';
export const SET_PLAYERS = 'SET_PLAYERS';
export const SET_SELECTED_PERSON = 'SET_SELECTED_PERSON';
export const SET_SELECTED_PLANET = 'SET_SELECTED_PLANET';
export const RESET_SET_ACTION = 'RESET_SET_ACTION';
